image: yawik/build

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

stages:
  - build
  - test

composer:
  stage: build
  cache:
    key: build-cache
    paths:
    - vendor/
  script:
    - composer install

phpunit:
  stage: test
  cache:
    key: build-cache
    paths:
      - vendor/
  script:
    - cp ./etc/travis/autoload/*.* config/autoload
    - ./vendor/bin/phpunit --debug

behat:
  stage: test
  cache:
    key: build-cache
    paths:
      - vendor/
  script:
    - cp ./etc/travis/autoload/*.* config/autoload
    - ./bin/start-selenium > /dev/null 2>&1 &
    - sleep 5
    - composer run serve --timeout=0 > /dev/null 2>&1 &
    - ./vendor/bin/behat --strict --no-interaction