image: yawik/build

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

stages:
  - build
  - test

composer:
  stage: build
  cache:
    key: build-cache
    paths:
    - vendor/
  script:
    - composer install

phpunit:
  stage: test
  cache:
    key: build-cache
    paths:
      - vendor/
  script:
    - ./vendor/bin/phpunit --debug

behat:
  stage: test
  cache:
    key: build-cache
    paths:
      - vendor/
  script:
    - echo "behat"
    - echo "try to integrate https://github.com/cross-solution/YAWIK/blob/master/etc/travis/behat-integration.yml" 
