image: php:7.4

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/


services:
  - mongo

before_script:
  - bash ci/docker_install.sh > /dev/null
  
stages:
  - test

test:yawik:
  script:
    - composer install
    - phpunit
    