# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - mkdir -p ~/.ssh
   - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
   - export PATH=$PATH:/usr/local/bin

after_script:
  - date

stages:
  - test

test:
  stage: test
  script:
    - pgrep ssh-agent
    - echo "do some tests"
